### ISSUE TITLE
Handling touch

### ISSUE THREAD

**Issue by saviormike** [linkov/fast-twitter-label#1]
Hi, currently I am trying to deploy this library in my project. I placed this one inside a UITableViewCell and my table view delegate set to present a segue in didSelectRow.

Now the problem is, can I stop the touch event from propagating to upper level of UIView? I tried exclusiveTouch but no luck with it.

**Comment by linkov** [comment]
Hi, you can try overriding ```- (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event``` in UIView subclass or setting ```[aView setUserInteractionEnabled:NO];```
